webtalk_init -webtalk_dir /home/jaehee2/Documents/gitrepos/fpga/sample_generator/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/sample_generator_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 16 07:50:14 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2700185" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211639666_1777540439_0_960" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f8cd07c0-ea4b-4fd8-96f3-d64087db9380" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0b0c36aa66e64404a3d5f2e61742be45" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "42" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 19.04" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2447.987 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "19 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115388_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3856042435 -regid "211639666_1777540439_0_960" -xml /home/jaehee2/Documents/gitrepos/fpga/sample_generator/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/sample_generator_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/jaehee2/Documents/gitrepos/fpga/sample_generator/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/sample_generator_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/jaehee2/Documents/gitrepos/fpga/sample_generator/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/sample_generator_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
