#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Mar 15 19:54:34 EDT 2020
# SW Build 2700185 on Thu Oct 24 18:45:48 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim sample_generator_testbench_behav -key {Behavioral:sim_1:Functional:sample_generator_testbench} -tclbatch sample_generator_testbench.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim sample_generator_testbench_behav -key {Behavioral:sim_1:Functional:sample_generator_testbench} -tclbatch sample_generator_testbench.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

